name: build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: '123456789abcd'
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check conventional commits
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci --ignore-scripts

      - name: Post-install
        run: npm rebuild && npm run prepare --if-present

      - name: Lint
        run: npm run lint

      - name: Prepare DB
        run: |
          npm run db:fill
        env:
          PGUSER: postgres
          PGDATABASE: test
          PGPASSWORD: 123456789abcd

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        env:
          PGUSER: postgres
          PGDATABASE: test
          PGPASSWORD: 123456789abcd

      - name: Coveralls
        if: ${{ github.event_name == 'push' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
